plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Shared classes for projects requiring GPG support"

dependencies {
    api(projects.resources)

    api(libs.bouncycastlePgp)
    api(libs.jspecify)

    implementation(projects.stdlibJavaExtensions)
    implementation(projects.time)
    implementation(projects.loggingApi)

    implementation(libs.bouncycastleProvider)
    implementation(libs.guava)

    testRuntimeOnly(projects.logging)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
