plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Public API interfaces for Gradle credentials"

dependencies {
    api(projects.baseServices)
    api(libs.jspecify)

    compileOnly(projects.internalInstrumentationApi) {
        because("Provides @ToBeReplacedByLazyProperty annotation, following the same pattern as core-api")
    }
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
