/*
 * Copyright 2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.buildinit.specs.internal

import org.gradle.api.logging.Logger
import org.gradle.api.logging.Logging.getLogger
import org.gradle.buildinit.specs.BuildInitGenerator
import org.gradle.buildinit.specs.BuildInitSpec
import org.gradle.internal.service.scopes.Scope
import org.gradle.internal.service.scopes.ServiceScope
import java.util.Map
import java.util.Optional
import java.util.function.Consumer
import java.util.function.Function
import java.util.function.Supplier
import java.util.stream.Collectors

/**
 * A registry of the available [BuildInitSpec]s that can be used to generate new projects via the `init` task.
 */
@ServiceScope(Scope.Build::class)
class BuildInitSpecRegistry {
    private val specsByGeneratorType: MutableMap<Class<out BuildInitGenerator>, MutableList<BuildInitSpec>> = HashMap<Class<out BuildInitGenerator>, MutableList<BuildInitSpec>>()

    /**
     * Register the given generator as providing the given.
     *
     *
     * This does not replace existing mappings for the same generator class, but appends to any that are already
     * present in the registry.  Attempting to register a spec for the same type with multiple generators will
     * produce an exception.
     *
     * @param generatorType generator class to use to generate specs
     * @param specs new [BuildInitSpec]s that can be generated by this generator
     */
    fun register(generatorType: Class<out BuildInitGenerator>, specs: MutableList<BuildInitSpec>) {
        val currentSpecsForGenerator = specsByGeneratorType.computeIfAbsent(generatorType) { k: Class<out BuildInitGenerator?>? -> ArrayList<BuildInitSpec?>() }
        specs.forEach(Consumer { spec: BuildInitSpec? ->
            doGetGeneratorForSpec(spec!!).ifPresent(Consumer { g: Class<out BuildInitGenerator?>? ->
                throw IllegalStateException(String.format("Spec: '%s' with type: '%s' cannot use same type as another spec already registered!", spec.getDisplayName(), spec.type))
            })
            currentSpecsForGenerator.add(spec)
            LOGGER.info("Loaded project spec: '{} ({})', generated via: '{}'", spec.getDisplayName(), spec.type, generatorType.getName())
        })
    }

    val allSpecs: MutableList<BuildInitSpec>
        get() = specsByGeneratorType.values.stream()
            .flatMap<BuildInitSpec> { obj: MutableList<BuildInitSpec?>? -> obj!!.stream() }
            .collect(Collectors.toList())

    val isEmpty: Boolean
        get() = specsByGeneratorType.isEmpty()

    /**
     * Returns the [BuildInitSpec] in the registry with the given type; throwing
     * an exception if there is not exactly one such spec.
     *
     * @param type the type of the project spec to find
     * @return the project spec with the given type
     */
    fun getSpecByType(type: String): BuildInitSpec {
        val matchingSpecs = specsByGeneratorType.values.stream()
            .flatMap<BuildInitSpec> { obj: MutableList<BuildInitSpec?>? -> obj!!.stream() }
            .filter { spec: BuildInitSpec? -> spec!!.type == type }
            .collect(Collectors.toList())

        when (matchingSpecs.size) {
            0 -> throw IllegalStateException(
                "Build init spec with type: '" + type + "' was not found!" + System.lineSeparator() +
                        "Known types:" + System.lineSeparator() +
                        this.allSpecs.stream()
                            .map<String> { obj: BuildInitSpec? -> obj!!.type }
                            .map<String> { t: String? -> " - " + t }
                            .collect(Collectors.joining(System.lineSeparator()))
            )

            1 -> return matchingSpecs.get(0)
            else -> throw IllegalStateException("Multiple project specs: " + matchingSpecs.stream().map<String> { obj: BuildInitSpec? -> obj!!.getDisplayName() }
                .collect(Collectors.joining(", ")) + " with type: '" + type + "' were found!")
        }
    }

    /**
     * Returns the [BuildInitGenerator] type that can be used to generate a project
     * with the given [BuildInitSpec].
     *
     *
     * This searches by project type.
     *
     * @param spec the project spec to find the generator for
     * @return the type of generator that can be used to generate a project with the given spec
     */
    fun getGeneratorForSpec(spec: BuildInitSpec): Class<out BuildInitGenerator> {
        return doGetGeneratorForSpec(spec).orElseThrow<IllegalStateException>(Supplier { IllegalStateException("Spec: '" + spec.getDisplayName() + "' with type: '" + spec.type + "' is not registered!") })
    }

    private fun doGetGeneratorForSpec(spec: BuildInitSpec): Optional<Class<out BuildInitGenerator>> {
        return specsByGeneratorType.entries.stream()
            .filter { entry: MutableMap.MutableEntry<Class<out BuildInitGenerator?>?, MutableList<BuildInitSpec?>?>? -> isSpecWithTypePresent(spec, entry!!.value) }
            .findFirst()
            .map<Class<out BuildInitGenerator>>(Function { Map.Entry.key })
    }

    private fun isSpecWithTypePresent(target: BuildInitSpec, toSearch: MutableList<BuildInitSpec>): Boolean {
        return toSearch.stream().anyMatch { s: BuildInitSpec? -> isSameType(s!!, target) }
    }

    private fun isSameType(s1: BuildInitSpec, s2: BuildInitSpec): Boolean {
        return s1.type == s2.type
    }

    companion object {
        const val BUILD_INIT_SPECS_PLUGIN_SUPPLIER: String = "org.gradle.buildinit.specs"

        private val LOGGER: Logger = getLogger(BuildInitSpecRegistry::class.java)!!
    }
}
