/*
 * Copyright 2012 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.api.reporting.internal

import com.googlecode.jatl.Html
import org.gradle.api.reporting.DirectoryReport
import org.gradle.api.reporting.Report
import org.gradle.reporting.HtmlPageBuilder
import org.gradle.reporting.HtmlReportRenderer
import org.gradle.reporting.ReportRenderer
import org.gradle.util.GradleVersion
import org.gradle.util.internal.RelativePathUtil
import java.io.File
import java.io.Writer
import java.util.Date
import java.util.TreeSet

class BuildDashboardGenerator : ReportRenderer<MutableCollection<Report>?, File?>() {
    private var reports: MutableSet<Report>? = null
    private var outputFile: File? = null

    public override fun render(reports: MutableCollection<Report>, outputFile: File) {
        this.reports = TreeSet<Report>(object : Comparator<Report> {
            override fun compare(o1: Report, o2: Report): Int {
                return o1.getDisplayName().compareTo(o2.getDisplayName())
            }
        })
        this.reports!!.addAll(reports)
        this.outputFile = outputFile

        val renderer = HtmlReportRenderer()
        renderer.renderRawSinglePage<MutableCollection<Report>?>(reports, object : ReportRenderer<MutableCollection<Report>?, HtmlPageBuilder<Writer>?>() {
            public override fun render(model: MutableCollection<Report>, builder: HtmlPageBuilder<Writer?>) {
                generate(builder)
            }
        }, outputFile)
    }

    private fun generate(builder: HtmlPageBuilder<Writer?>) {
        val baseCssLink = builder.requireResource(javaClass.getResource("/org/gradle/reporting/base-style.css"))
        val cssLink = builder.requireResource(javaClass.getResource("style.css"))
        object : Html(builder.output) {
            init {
                html()
                head()
                meta().httpEquiv("Content-Type").content("text/html; charset=utf-8")
                meta().httpEquiv("x-ua-compatible").content("IE=edge")
                link().rel("stylesheet").type("text/css").href(baseCssLink).end()
                link().rel("stylesheet").type("text/css").href(cssLink).end()
                title().text("Build dashboard").end()
                end()
                body()
                div().id("content")
                if (reports!!.size > 0) {
                    h1().text("Build reports").end()
                    ul()
                    for (report in reports!!) {
                        li()
                        if (report.getOutputLocation().get().getAsFile().exists()) {
                            a().href(RelativePathUtil.relativePath(outputFile!!.getParentFile(), getHtmlLinkedFileFromReport(report))).text(report.getDisplayName())
                        } else {
                            span().classAttr("unavailable").text(report.getDisplayName())
                        }
                        end(2)
                    }
                    end()
                } else {
                    h1().text("There are no build reports available.").end()
                }
                div().id("footer")
                p()
                text("Generated by ")
                a().href("https://www.gradle.org").text(GradleVersion.current().toString()).end()
                text(" at " + builder.formatDate(Date()))
                end()
                end()
                end()
                endAll()
            }
        }
    }

    private fun getHtmlLinkedFileFromReport(report: Report): File {
        if (report is DirectoryReport) {
            return report.getEntryPoint()
        } else {
            return report.getOutputLocation().get().getAsFile()
        }
    }
}
