plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Internal implementation of Gradle authentication container"

dependencies {
    api(projects.baseServices)
    api(projects.coreApi)
    api(projects.credentials)
    api(projects.credentialsApi)
    api(projects.domainObjectCollections)
    api(projects.serviceProvider)

    api(libs.inject)
    api(libs.jspecify)

    implementation(projects.stdlibJavaExtensions) {
        because("Provides @NullMarked")
    }

    testImplementation(testFixtures(projects.core))
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
