plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Implementations for TAPI IDE models"

dependencies {
    api(projects.baseServices)
    api(projects.clientServices)
    api(projects.stdlibJavaExtensions)
    api(projects.toolingApi)
    api(libs.jspecify)

    implementation(projects.classloaders)
    implementation(libs.guava)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    requiredRuntimes {
        client = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
