plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Internal API for Gradle authentication schemes"

dependencies {
    api(projects.baseServices)
    api(projects.credentialsApi)
    api(projects.stdlibJavaExtensions)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
