/*
 * Copyright 2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.testing.jacoco.tasks

import com.google.common.base.Predicate
import com.google.common.collect.Iterables
import org.gradle.api.Action
import org.gradle.api.Incubating
import org.gradle.api.Task
import org.gradle.api.file.FileCollection
import org.gradle.api.specs.Spec
import org.gradle.api.tasks.Classpath
import org.gradle.api.tasks.IgnoreEmptyDirectories
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.SourceSet
import org.gradle.api.tasks.TaskCollection
import org.gradle.internal.instrumentation.api.annotations.NotToBeReplacedByLazyProperty
import org.gradle.testing.jacoco.plugins.JacocoTaskExtension
import org.gradle.work.DisableCachingByDefault
import java.io.File
import java.util.Arrays
import java.util.concurrent.Callable
import javax.inject.Inject

/**
 * Base class for Jacoco report tasks.
 *
 * @since 3.4
 */
@DisableCachingByDefault(because = "Abstract super-class, not to be instantiated directly")
abstract class JacocoReportBase : JacocoBase() {
    init {
        onlyIf("Any of the execution data files exists", object : Spec<Task?> {
            override fun isSatisfiedBy(element: Task?): Boolean {
                return Iterables.any<File?>(this.executionData, object : Predicate<File?> {
                    override fun apply(file: File): Boolean {
                        return file.exists()
                    }
                })
            }
        })
    }

    @get:Inject
    protected abstract val instantiator: Instantiator?

    @get:Inject
    protected abstract val objectFactory: ObjectFactory?

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val executionData: ConfigurableFileCollection?

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:IgnoreEmptyDirectories
    abstract val sourceDirectories: ConfigurableFileCollection?

    @get:Classpath
    abstract val classDirectories: ConfigurableFileCollection?

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:IgnoreEmptyDirectories
    @get:Optional
    abstract val additionalClassDirs: ConfigurableFileCollection?

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:IgnoreEmptyDirectories
    @get:Optional
    abstract val additionalSourceDirs: ConfigurableFileCollection?

    @get:Input
    @get:Optional
    @get:Incubating
    abstract val sourceEncoding: Property<String?>?

    /**
     * Adds execution data files to be used during coverage analysis.
     *
     * @param files one or more files to add
     */
    fun executionData(vararg files: Any?) {
        this.executionData.from(*files)
    }

    /**
     * Adds execution data generated by a task to the list of those used during coverage analysis. Only tasks with a [JacocoTaskExtension] will be included; all others will be ignored.
     *
     * @param tasks one or more tasks to add
     */
    fun executionData(vararg tasks: Task) {
        for (task in tasks) {
            val extension: JacocoTaskExtension? = task.getExtensions().findByType<JacocoTaskExtension?>(JacocoTaskExtension::class.java)
            if (extension != null) {
                executionData(object : Callable<File?> {
                    override fun call(): File? {
                        return extension.getDestinationFile()
                    }
                })
                mustRunAfter(task)
            }
        }
    }

    /**
     * Adds execution data generated by the given tasks to the list of those used during coverage analysis. Only tasks with a [JacocoTaskExtension] will be included; all others will be ignored.
     *
     * @param tasks one or more tasks to add
     */
    fun executionData(tasks: TaskCollection<*>) {
        tasks.all(Action { tasks: Task? -> this.executionData(tasks) })
    }

    @get:NotToBeReplacedByLazyProperty(because = "Not settable FileCollection", willBeDeprecated = true)
    @get:Internal
    val allClassDirs: FileCollection
        /**
         * Gets the class directories that coverage will be reported for. All classes in these directories will be included in the report.
         *
         * @return class dirs to report coverage of
         */
        get() = this.classDirectories.plus(this.additionalClassDirs)

    @get:NotToBeReplacedByLazyProperty(because = "Not settable FileCollection", willBeDeprecated = true)
    @get:Internal
    val allSourceDirs: FileCollection
        /**
         * Gets the source directories for the classes that will be reported on. Source will be obtained from these directories only for the classes included in the report.
         *
         * @return source directories for the classes reported on
         * @see .getAllClassDirs
         */
        get() = this.sourceDirectories.plus(this.additionalSourceDirs)

    /**
     * Adds a source set to the list to be reported on. The output of this source set will be used as classes to include in the report. The source for this source set will be used for any classes
     * included in the report.
     *
     * @param sourceSets one or more source sets to report on
     */
    fun sourceSets(vararg sourceSets: SourceSet) {
        for (sourceSet in sourceSets) {
            this.sourceDirectories.from(object : Callable<MutableSet<File?>?> {
                @Throws(Exception::class)
                override fun call(): MutableSet<File?> {
                    return sourceSet.allJava.getSrcDirs()
                }
            })
            this.classDirectories.from(sourceSet.output)
        }
    }

    /**
     * Adds additional class directories to those that will be included in the report.
     *
     * @param dirs one or more directories containing classes to report coverage of
     */
    fun additionalClassDirs(vararg dirs: File?) {
        additionalClassDirs(this.objectFactory.fileCollection().from(Arrays.asList<File?>(*dirs)))
    }

    /**
     * Adds additional class directories to those that will be included in the report.
     *
     * @param dirs a `FileCollection` of directories containing classes to report coverage of
     */
    fun additionalClassDirs(dirs: FileCollection) {
        this.additionalClassDirs.from(dirs)
    }

    /**
     * Adds additional source directories to be used for any classes included in the report.
     *
     * @param dirs one or more directories containing source files for the classes included in the report
     */
    fun additionalSourceDirs(vararg dirs: File?) {
        additionalSourceDirs(this.objectFactory.fileCollection().from(Arrays.asList<File?>(*dirs)))
    }

    /**
     * Adds additional source directories to be used for any classes included in the report.
     *
     * @param dirs a `FileCollection` of directories containing source files for the classes included in the report
     */
    fun additionalSourceDirs(dirs: FileCollection) {
        this.additionalSourceDirs.from(dirs)
    }
}
