/*
 * Copyright 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.testing.jacoco.tasks

import groovy.lang.Closure
import org.gradle.api.Action
import org.gradle.api.reporting.Reporting
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Nested
import org.gradle.api.tasks.TaskAction
import org.gradle.internal.Describables
import org.gradle.internal.jacoco.AntJacocoReport
import org.gradle.internal.jacoco.JacocoReportParameters
import org.gradle.internal.jacoco.JacocoReportsContainerImpl
import org.gradle.util.internal.ClosureBackedAction
import javax.inject.Inject

/**
 * Task to generate HTML, Xml and CSV reports of Jacoco coverage data.
 */
@CacheableTask
abstract class JacocoReport : JacocoReportBase(), Reporting<JacocoReportsContainer?> {
    private val reports: JacocoReportsContainer

    init {
        this.reportProjectName.value(getProject().getName()).disallowChanges()
        reports = getProject().getObjects().newInstance<JacocoReportsContainerImpl>(JacocoReportsContainerImpl::class.java, Describables.quoted("Task", getIdentityPath()))
    }

    @get:Input
    abstract val reportProjectName: Property<String?>?

    /**
     * Returns the reports to be generated by this task.
     */
    @Nested
    override fun getReports(): JacocoReportsContainer {
        return reports
    }

    /**
     * Configures the reports to be generated by this task.
     */
    override fun reports(closure: Closure<*>): JacocoReportsContainer {
        return reports(ClosureBackedAction<JacocoReportsContainer?>(closure))
    }

    override fun reports(configureAction: Action<in JacocoReportsContainer?>): JacocoReportsContainer {
        configureAction.execute(reports)
        return reports
    }

    @get:Inject
    protected abstract val workerExecutor: WorkerExecutor?

    @TaskAction
    fun generate() {
        val queue = this.workerExecutor.classLoaderIsolation()

        queue.submit<JacocoReportParameters?>(AntJacocoReport::class.java, Action { parameters: JacocoReportParameters? ->
            parameters!!.antLibraryClasspath.convention(getJacocoClasspath())
            parameters.projectName.convention(this.reportProjectName)
            parameters.encoding.convention(getSourceEncoding())
            parameters.allSourcesDirs.convention(getAllSourceDirs())
            parameters.allClassesDirs.convention(getAllClassDirs())
            parameters.executionData.convention(getExecutionData())

            parameters.generateHtml.convention(reports.getHtml().getRequired())
            parameters.htmlDestination.convention(reports.getHtml().getOutputLocation())
            parameters.generateXml.convention(reports.getXml().getRequired())
            parameters.xmlDestination.convention(reports.getXml().getOutputLocation())
            parameters.generateCsv.convention(reports.getCsv().getRequired())
            parameters.csvDestination.convention(reports.getCsv().getOutputLocation())
        })
    }
}
