plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Contains classes for instrumentation reporting, e.g. bytecode upgrades. " +
    "Note: For Configuration cache reporting see configuration-cache/input-tracking project."

dependencies {
    api(projects.internalInstrumentationApi)
    api(projects.stdlibJavaExtensions)

    api(libs.jspecify)

    integTestDistributionRuntimeOnly(projects.distributionsJvm)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}



errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
