plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Internal API for composing service registries"

dependencies {
    api(projects.serviceLookup)
    api(projects.serviceProvider)
    api(projects.stdlibJavaExtensions)

    implementation(projects.serviceRegistryImpl)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
