plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Implements logic for generating jacoco reports"

dependencies {
    api(projects.ant)
    api(projects.antWorker)
    api(projects.baseServices)
    api(projects.coreApi)

    api(projects.internalInstrumentationApi)
    api(libs.jspecify)

    implementation(projects.daemonServerWorker)
    implementation(projects.stdlibJavaExtensions)
    implementation(libs.guava)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    requiredRuntimes {
        worker = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
