plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Kotlin DSL Tooling Models for IDEs (Legacy)"

dependencies {
    api(libs.jspecify)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
    }
}

// Kotlin DSL tooling models should not be part of the public API
// TODO Find a way to not register this and the task instead
configurations.remove(configurations.apiStubElements.get())

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
