plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "The Gradle build option parser."

dependencies {
    api(projects.cli)
    api(projects.stdlibJavaExtensions)

    api(libs.jspecify)

    implementation(projects.baseServices)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
