/*
 * Copyright 2011 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.reporting

import org.gradle.internal.html.SimpleHtmlWriter
import org.gradle.util.GradleVersion
import java.io.IOException
import java.net.URL
import java.util.Date

abstract class TabbedPageRenderer<T> : ReportRenderer<T, HtmlPageBuilder<SimpleHtmlWriter>>() {
    protected var model: T? = null
        private set

    protected abstract val title: String

    protected abstract val headerRenderer: ReportRenderer<T?, SimpleHtmlWriter?>?

    protected abstract val contentRenderer: ReportRenderer<T?, SimpleHtmlWriter?>?

    protected open val pageTitle: String
        get() = this.title

    protected abstract val styleUrl: URL?

    @Throws(IOException::class)
    override fun render(model: T?, builder: HtmlPageBuilder<SimpleHtmlWriter>?) {
        val pageBuilder = builder!!
        this.model = model

        val title = this.title
        val baseStyleLink = pageBuilder.requireResource(BASE_STYLE_URL!!)
        val reportJsLink = pageBuilder.requireResource(REPORT_JS_URL!!)
        val styleLink = pageBuilder.requireResource(this.styleUrl!!)

        val htmlWriter = pageBuilder.output

        htmlWriter.startElement("head")
            .startElement("meta").attribute("http-equiv", "Content-Type").attribute("content", "text/html; charset=utf-8").endElement()
            .startElement("meta").attribute("http-equiv", "x-ua-compatible").attribute("content", "IE=edge").endElement()
            .startElement("title").characters(this.pageTitle).endElement()
            .startElement("link").attribute("href", baseStyleLink).attribute("rel", "stylesheet").attribute("type", "text/css").endElement()
            .startElement("link").attribute("href", styleLink).attribute("rel", "stylesheet").attribute("type", "text/css").endElement()
            .startElement("script").attribute("src", reportJsLink).attribute("type", "text/javascript").characters("").endElement() //html does not like <a name="..."/>
            .endElement()

        htmlWriter.startElement("body")
            .startElement("div").attribute("id", "content")
        if (!title.isEmpty()) {
            htmlWriter.startElement("h1").characters(title).endElement()
        }

        this.headerRenderer!!.render(model, htmlWriter)
        this.contentRenderer!!.render(model, htmlWriter)

        htmlWriter.startElement("div").attribute("id", "footer")
            .startElement("p")
            .startElement("div")
            .startElement("label")
            .attribute("class", "hidden")
            .attribute("id", "label-for-line-wrapping-toggle")
            .attribute("for", "line-wrapping-toggle")
            .characters("Wrap lines")
            .startElement("input")
            .attribute("id", "line-wrapping-toggle")
            .attribute("type", "checkbox")
            .attribute("autocomplete", "off")
            .endElement()
            .endElement()
            .endElement()
            .characters("Generated by ")
            .startElement("a").attribute("href", "https://www.gradle.org").characters("Gradle " + GradleVersion.current().getVersion()).endElement()
            .characters(String.format(" at %s", pageBuilder.formatDate(Date())))
            .endElement()
            .endElement()
            .endElement()
            .endElement()
    }

    companion object {
        private val BASE_STYLE_URL: URL? = TabbedPageRenderer::class.java.getResource("/org/gradle/reporting/base-style.css")
        private val REPORT_JS_URL: URL? = TabbedPageRenderer::class.java.getResource("/org/gradle/reporting/report.js")
    }
}
