plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Process execution public API types."

dependencies {
    api(projects.stdlibJavaExtensions)

    api(libs.jspecify)

    compileOnly(projects.internalInstrumentationApi)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
