plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Implementations for TAPI native models"

dependencies {
    api(projects.ideModelImpls)
    api(projects.toolingApi)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    requiredRuntimes {
        client = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
    }
}

repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
