plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Process memory abstractions."

dependencies {
    api(projects.concurrent)
    api(projects.stdlibJavaExtensions)
    api(projects.baseServices)
    api(projects.messaging)

    api(libs.jspecify)

    implementation(projects.native)
    implementation(projects.serviceLookup)

    implementation(libs.slf4jApi)
    implementation(libs.guava)
    implementation(libs.nativePlatform)

    testImplementation(testFixtures(projects.core))

    integTestDistributionRuntimeOnly(projects.distributionsCore)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

packageCycles {
    excludePatterns.add("org/gradle/process/internal/**")
}

repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
