plugins {
    id("gradlebuild.distribution.api-java")
    id("gradlebuild.publish-public-libraries")
    kotlin("jvm")
}

description = "Develocity plugin dependencies that also need to be exposed to workers"

dependencies {
    api(libs.jspecify)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    requiredRuntimes {
        worker = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
