/*
 * Copyright 2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.api.internal.tasks.compile.incremental.processing

import org.gradle.api.internal.tasks.compile.incremental.compilerapi.deps.GeneratedResource
import java.io.Serializable

/**
 * Contains all the data necessary to make annotation processing incremental.
 */
class AnnotationProcessingResult : Serializable {
    /**
     * Contains the types generated by isolating annotation processors, grouped by the type they were generated from.
     */
    val generatedTypesWithIsolatedOrigin: MutableMap<String?, MutableSet<String?>?> = LinkedHashMap<String?, MutableSet<String?>?>()

    /**
     * Contains the resources generated by isolating annotation processors, grouped by the type they were generated from.
     */
    val generatedResourcesWithIsolatedOrigin: MutableMap<String?, MutableSet<GeneratedResource?>?> = LinkedHashMap<String?, MutableSet<GeneratedResource?>?>()

    /**
     * Contains the types that aggregating annotation processors registered themselves for.
     * These types need to be reprocessed no matter what source changes are made to ensure that the generated types contain all relevant information.
     */
    @JvmField
    val aggregatedTypes: MutableSet<String?> = HashSet<String?>()

    /**
     * Contains the types that aggregating annotation processors generated.
     * These types need to be recompiled on any source change, because it may not be clear where these types came from and whether they are now stale.
     */
    val generatedAggregatingTypes: MutableSet<String?> = HashSet<String?>()

    /**
     * Contains the resources that aggregating annotation processors generated.
     * These resources need to be recreated on any source change, because it may not be clear where these resources came from and whether they are now stale.
     */
    val generatedAggregatingResources: MutableSet<GeneratedResource?> = HashSet<GeneratedResource?>()
    @JvmField
    val annotationProcessorResults: MutableList<AnnotationProcessorResult?> = ArrayList<AnnotationProcessorResult?>()
    @JvmField
    var fullRebuildCause: String? = null

    fun addGeneratedType(name: String?, originatingElements: MutableSet<String?>) {
        for (originatingElement in originatingElements) {
            var derived = generatedTypesWithIsolatedOrigin.get(originatingElement)
            if (derived == null) {
                derived = LinkedHashSet<String?>()
                generatedTypesWithIsolatedOrigin.put(originatingElement, derived)
            }
            derived.add(name)
        }
    }

    fun addGeneratedResource(resource: GeneratedResource?, originatingElements: MutableSet<String?>) {
        for (originatingElement in originatingElements) {
            var derived = generatedResourcesWithIsolatedOrigin.get(originatingElement)
            if (derived == null) {
                derived = LinkedHashSet<GeneratedResource?>()
                generatedResourcesWithIsolatedOrigin.put(originatingElement, derived)
            }
            derived.add(resource)
        }
    }
}
