plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Internal API for Gradle's Ant integration"

strictCompile {
    ignoreRawTypes() // raw types in BuilderSupport overrides (AntBuilderDelegate) and Groovy internals (BasicAntBuilder)
}

dependencies {
    api(projects.antApi)
    api(projects.baseServices)
    api(projects.coreApi)                 // Logger, LogLevel
    api(projects.stdlibJavaExtensions)
    api(libs.ant)                         // AntLoggingAdapter implements BuildLogger

    implementation(libs.groovy)
    implementation(projects.logging)      // LogLevelMapping
    implementation(projects.loggingApi)   // LogLevelMapping (transitive)
    implementation(projects.modelCore)    // DynamicObject, DynamicObjectUtil (AntBuilderDelegate)
    implementation(libs.groovyAnt)        // AntBuilderDelegate wraps groovy.ant.AntBuilder

    compileOnly(libs.jetbrainsAnnotations)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
