plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Provides high-level insights into a Gradle build (--profile)"

dependencies {
    api(projects.stdlibJavaExtensions)
    api(projects.serviceProvider)
    api(projects.time)
    api(projects.baseServices)
    api(projects.core)
    api(projects.coreApi)
    api(projects.enterpriseLogging)
    api(projects.startParameter)

    api(libs.jspecify)

    implementation(projects.logging)
    implementation(projects.loggingApi)
    implementation(projects.reportRendering)

    implementation(libs.guava)

    testImplementation(projects.internalTesting)

    integTestImplementation(libs.jsoup)

    integTestDistributionRuntimeOnly(projects.distributionsFull)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    requiredRuntimes {
        daemon = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
    }
}


repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
