plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Implements the work to generate scaladoc"

dependencies {
    api(projects.coreApi)
    api(projects.daemonServerWorker)
    api(libs.inject)

    implementation(projects.baseServices)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    requiredRuntimes {
        worker = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
