plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Contains classes which all compiler workers leverage, regardless of ecosystem"

dependencies {
    api(projects.coreApi)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    requiredRuntimes {
        worker = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
