plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Marker class file used to locate the Gradle distribution base directory"

gradleModule {
    requiredRuntimes {
        client = true
        daemon = true
        worker = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

// Installation beacon should not be part of the public API
// TODO Find a way to not register this and the task instead
configurations.remove(configurations.apiStubElements.get())

// This lib should not have any dependencies.

errorprone {
    nullawayEnabled = true
}
dependencies {
    implementation(kotlin("stdlib-jdk8"))
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
