plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Configuration input discovery code"

dependencies {
    api(libs.jspecify)
    api(libs.guava)

    integTestDistributionRuntimeOnly(projects.distributionsCore)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
