/*
 * Copyright 2010 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.api.tasks.wrapper

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.Incubating
import org.gradle.api.internal.file.FileOperations
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.options.Option
import org.gradle.api.tasks.wrapper.internal.GradleVersionResolver
import org.gradle.api.tasks.wrapper.internal.WrapperDefaults
import org.gradle.api.tasks.wrapper.internal.WrapperGenerator
import org.gradle.internal.UncheckedException.Companion.throwAsUncheckedException
import org.gradle.internal.deprecation.DeprecationLogger.deprecateMethod
import org.gradle.internal.instrumentation.api.annotations.ToBeReplacedByLazyProperty
import org.gradle.util.GradleVersion
import org.gradle.util.internal.GUtil
import org.gradle.util.internal.WrapperDistributionUrlConverter.convertDistributionUrl
import org.gradle.work.DisableCachingByDefault
import org.gradle.wrapper.Download
import org.gradle.wrapper.Logger
import org.gradle.wrapper.WrapperExecutor
import java.io.File
import java.io.IOException
import java.net.URI
import java.net.URISyntaxException
import java.nio.file.Files
import java.nio.file.Paths
import java.util.Arrays
import java.util.Properties
import javax.inject.Inject

/**
 *
 * Generates scripts (for *nix and windows) which allow you to build your project with Gradle, without having to
 * install Gradle.
 *
 *
 * When a user executes a wrapper script the first time, the script downloads and installs the appropriate Gradle
 * distribution and runs the build against this downloaded distribution. Any installed Gradle distribution is ignored
 * when using the wrapper scripts.
 *
 *
 * The scripts generated by this task are intended to be committed to your version control system. This task also
 * generates a small `gradle-wrapper.jar` bootstrap JAR file and properties file which should also be committed to
 * your VCS. The scripts delegate to this JAR.
 */
@DisableCachingByDefault(because = "Updating the wrapper is not worth caching")
abstract class Wrapper : DefaultTask() {
    /**
     * Specifies the Gradle distribution type.
     */
    enum class DistributionType {
        /**
         * binary-only Gradle distribution without sources and documentation
         */
        BIN,

        /**
         * complete Gradle distribution with binaries, sources and documentation
         */
        ALL
    }

    /**
     * Specifies how the wrapper path should be interpreted.
     */
    enum class PathBase {
        PROJECT, GRADLE_USER_HOME
    }


    private val gradleVersionResolver: GradleVersionResolver

    private var scriptFile: Any? = WrapperDefaults.SCRIPT_PATH
    private var jarFile: Any? = WrapperDefaults.JAR_FILE_PATH
    /**
     * Returns the path where the gradle distributions needed by the wrapper are unzipped. The path is relative to the
     * distribution base directory
     *
     * @see .setDistributionPath
     */
    /**
     * Sets the path where the gradle distributions needed by the wrapper are unzipped. The path is relative to the
     * distribution base directory
     *
     * @see .setDistributionPath
     */
    @get:ToBeReplacedByLazyProperty
    @get:Input
    var distributionPath: String = DEFAULT_DISTRIBUTION_PARENT_NAME
    /**
     * The distribution base specifies whether the unpacked wrapper distribution should be stored in the project or in
     * the gradle user home dir.
     */
    /**
     * The distribution base specifies whether the unpacked wrapper distribution should be stored in the project or in
     * the gradle user home dir.
     */
    @get:ToBeReplacedByLazyProperty
    @get:Input
    var distributionBase: PathBase = WrapperDefaults.DISTRIBUTION_BASE

    @get:ToBeReplacedByLazyProperty
    @get:Input
    @set:Option(option = "gradle-distribution-url", description = "The URL to download the Gradle distribution from.")
    var distributionUrl: String? = null
        /**
         * The URL to download the gradle distribution from.
         *
         *
         * If not set, the download URL is the default for the specified [.getGradleVersion].
         *
         *
         * If [.getGradleVersion] is not set, will return null.
         *
         *
         * The wrapper downloads a certain distribution only once and caches it. If your distribution base is the
         * project, you might submit the distribution to your version control system. That way no download is necessary at
         * all. This might be in particular interesting, if you provide a custom gradle snapshot to the wrapper, because you
         * don't need to provide a download server then.
         */
        get() {
            if (field != null) {
                return field
            }

            return WrapperGenerator.getDistributionUrl(this.resolvedGradleVersion, distributionType)
        }
        /**
         * The URL to download the gradle distribution from.
         *
         *
         * If not set, the download URL is the default for the specified [.getGradleVersion].
         *
         *
         * If [.getGradleVersion] is not set, will return null.
         *
         *
         * The wrapper downloads a certain distribution and caches it. If your distribution base is the
         * project, you might submit the distribution to your version control system. That way no download is necessary at
         * all. This might be in particular interesting, if you provide a custom gradle snapshot to the wrapper, because you
         * don't need to provide a download server then.
         *
         *
         * The distribution url is validated before it is written to the gradle-wrapper.properties file.
         */
        set(url) {
            distributionUrlConfigured = true
            field = url
        }
    /**
     * The SHA-256 hash sum of the gradle distribution.
     *
     *
     * If not set, the hash sum of the gradle distribution is not verified.
     *
     *
     * The wrapper allows for verification of the downloaded Gradle distribution via SHA-256 hash sum comparison.
     * This increases security against targeted attacks by preventing a man-in-the-middle attacker from tampering with
     * the downloaded Gradle distribution.
     *
     * @since 4.5
     */
    /**
     * The SHA-256 hash sum of the gradle distribution.
     *
     *
     * If not set, the hash sum of the gradle distribution is not verified.
     *
     *
     * The wrapper allows for verification of the downloaded Gradle distribution via SHA-256 hash sum comparison.
     * This increases security against targeted attacks by preventing a man-in-the-middle attacker from tampering with
     * the downloaded Gradle distribution.
     *
     * @since 4.5
     */
    @get:ToBeReplacedByLazyProperty
    @get:Input
    @get:Optional
    @set:Option(option = "gradle-distribution-sha256-sum", description = "The SHA-256 hash sum of the gradle distribution.")
    var distributionSha256Sum: String? = null
    /**
     * Returns the type of the Gradle distribution to be used by the wrapper.
     *
     * @see .setDistributionType
     */
    /**
     * The type of the Gradle distribution to be used by the wrapper. By default, this is [DistributionType.BIN],
     * which is the binary-only Gradle distribution without documentation.
     *
     * @see DistributionType
     */
    @get:ToBeReplacedByLazyProperty
    @get:Input
    @set:Option(option = "distribution-type", description = "The type of the Gradle distribution to be used by the wrapper.")
    var distributionType: DistributionType = WrapperDefaults.DISTRIBUTION_TYPE
    /**
     * Returns the path where the gradle distributions archive should be saved (i.e. the parent dir). The path is
     * relative to the archive base directory.
     */
    /**
     * Set's the path where the gradle distributions archive should be saved (i.e. the parent dir). The path is relative
     * to the parent dir specified with [.getArchiveBase].
     */
    @get:ToBeReplacedByLazyProperty
    @get:Input
    var archivePath: String = WrapperDefaults.ARCHIVE_PATH
    /**
     * The archive base specifies whether the unpacked wrapper distribution should be stored in the project or in the
     * gradle user home dir.
     */
    /**
     * The archive base specifies whether the unpacked wrapper distribution should be stored in the project or in the
     * gradle user home dir.
     */
    @get:ToBeReplacedByLazyProperty
    @get:Input
    var archiveBase: PathBase = WrapperDefaults.ARCHIVE_BASE
    private var distributionUrlConfigured = false
    private val isOffline = getProject().getGradle().getStartParameter().isOffline()

    @TaskAction
    fun generate() {
        val jarFileDestination = getJarFile()
        val unixScript = getScriptFile()
        val resolver = this.fileLookup.getFileResolver(unixScript.getParentFile())
        val jarFileRelativePath = resolver.resolveAsRelativePath(jarFileDestination)
        val propertiesFile = this.propertiesFile
        val existingProperties = if (propertiesFile.exists()) GUtil.loadProperties(propertiesFile) else null

        checkProperties(existingProperties)
        validateDistributionUrl(propertiesFile.getParentFile())

        WrapperGenerator.generate(
            archiveBase, archivePath,
            distributionBase, distributionPath,
            getDistributionSha256Sum(existingProperties),
            propertiesFile,
            jarFileDestination, jarFileRelativePath,
            unixScript, this.batchScript,
            this.distributionUrl,
            this.validateDistributionUrl.get(),
            this.networkTimeout.getOrNull(),
            this.retries.getOrNull(),
            this.retryBackOffMs.getOrNull()
        )
    }

    private fun checkProperties(existingProperties: Properties?) {
        val checksumProperty = if (existingProperties != null)
            existingProperties.getProperty(WrapperExecutor.DISTRIBUTION_SHA_256_SUM, null)
        else
            null

        if (!this.isCurrentVersion && distributionSha256Sum == null && checksumProperty != null) {
            throw GradleException("gradle-wrapper.properties contains distributionSha256Sum property, but the wrapper configuration does not have one. Specify one in the wrapper task configuration or with the --gradle-distribution-sha256-sum task option. You can find checksums for all Gradle releases at https://gradle.org/release-checksums")
        }
    }

    init {
        this.validateDistributionUrl.convention(WrapperDefaults.VALIDATE_DISTRIBUTION_URL)

        gradleVersionResolver = GradleVersionResolver(getProject().getResources().getText())
    }

    private fun validateDistributionUrl(uriRoot: File?) {
        if (distributionUrlConfigured && this.validateDistributionUrl.get()) {
            val url = this.distributionUrl!!
            val uri: URI = getDistributionUri(uriRoot, url)
            if (uri.getScheme() == "file") {
                if (!Files.exists(Paths.get(uri).toAbsolutePath())) {
                    throw throwAsUncheckedException(IOException(String.format(DISTRIBUTION_URL_EXCEPTION_MESSAGE, url)), true)
                }
            } else if (uri.getScheme().startsWith("http") && !isOffline) {
                try {
                    Download(Logger(true), "gradlew", Download.UNKNOWN_VERSION).sendHeadRequest(uri)
                } catch (e: Exception) {
                    throw throwAsUncheckedException(IOException(String.format(DISTRIBUTION_URL_EXCEPTION_MESSAGE, url), e), true)
                }
            }
        }
    }

    private fun getDistributionSha256Sum(existingProperties: Properties?): String? {
        if (distributionSha256Sum != null) {
            return distributionSha256Sum
        } else if (this.isCurrentVersion && existingProperties != null) {
            return existingProperties.getProperty(WrapperExecutor.DISTRIBUTION_SHA_256_SUM, null)
        } else {
            return null
        }
    }

    /**
     * Returns the file to write the wrapper script to.
     */
    @OutputFile
    @ToBeReplacedByLazyProperty
    fun getScriptFile(): File {
        return getServices().get<FileOperations?>(FileOperations::class.java)!!.file(scriptFile!!)
    }

    /**
     * The file to write the wrapper script to.
     *
     * @since 4.0
     */
    fun setScriptFile(scriptFile: File?) {
        this.scriptFile = scriptFile
    }

    /**
     * The file to write the wrapper script to.
     */
    fun setScriptFile(scriptFile: Any?) {
        this.scriptFile = scriptFile
    }

    @get:ToBeReplacedByLazyProperty
    @get:OutputFile
    val batchScript: File
        /**
         * Returns the file to write the wrapper batch script to.
         */
        get() = WrapperGenerator.getBatchScript(getScriptFile())

    /**
     * Returns the file to write the wrapper jar file to.
     */
    @OutputFile
    @ToBeReplacedByLazyProperty
    fun getJarFile(): File {
        return getServices().get<FileOperations?>(FileOperations::class.java)!!.file(jarFile!!)
    }

    /**
     * The file to write the wrapper jar file to.
     *
     * @since 4.0
     */
    fun setJarFile(jarFile: File?) {
        this.jarFile = jarFile
    }

    /**
     * The file to write the wrapper jar file to.
     */
    fun setJarFile(jarFile: Any?) {
        this.jarFile = jarFile
    }

    @get:ToBeReplacedByLazyProperty
    @get:OutputFile
    val propertiesFile: File
        /**
         * Returns the file to write the wrapper properties to.
         */
        get() = WrapperGenerator.getPropertiesFile(getJarFile())

    @get:ToBeReplacedByLazyProperty
    @get:Input
    @set:Option(
        option = "gradle-version", description = "The version of the Gradle distribution required by the wrapper. " +
                "The following labels are allowed: latest, release-candidate, release-milestone, release-nightly, and nightly."
    )
    var gradleVersion: String?
        /**
         * Returns the gradle version for the wrapper.
         *
         * @throws GradleException if the label that can be provided via [.setGradleVersion] can not be resolved at the moment. For example, there is not a `release-candidate` available at all times.
         * @see .setGradleVersion
         */
        get() = this.resolvedGradleVersion.getVersion()
        /**
         * The version of the gradle distribution required by the wrapper.
         * This is usually the same version of Gradle you use for building your project.
         * The following labels are allowed to specify a version: `latest`, `release-candidate`, `release-milestone`, `release-nightly`, and `nightly`
         *
         *
         * The resulting distribution url is validated before it is written to the gradle-wrapper.properties file.
         */
        set(gradleVersion) {
            distributionUrlConfigured = true
            setUnresolvedGradleVersion(gradleVersion!!)
        }

    @get:Deprecated("Since 9.3.0. Use {@link DistributionType#values()} directly instead.")
    @get:Internal
    val availableDistributionTypes: MutableList<DistributionType?>
        /**
         * The list of available gradle distribution types. Always returns the contents of [DistributionType.values].
         */
        get() {
            deprecateMethod(Wrapper::class.java, "getAvailableDistributionTypes")
                .replaceWith("Wrapper.DistributionType.values()")!!
                .willBeRemovedInGradle10()
                .withUpgradeGuideSection(9, "deprecated_wrapper_get_available_distribution_types")!!
                .nagUser()
            return Arrays.asList<DistributionType?>(*DistributionType.entries.toTypedArray())
        }

    private val isCurrentVersion: Boolean
        get() = GradleVersion.current() == this.resolvedGradleVersion

    private val resolvedGradleVersion: GradleVersion
        get() = gradleVersionResolver.getGradleVersion()

    private fun setUnresolvedGradleVersion(gradleVersion: String) {
        this.gradleVersionResolver.setGradleVersionRequest(gradleVersion)
    }

    @get:Option(option = "network-timeout", description = "Timeout in ms to use when the wrapper is performing network operations.")
    @get:Optional
    @get:Input
    abstract val networkTimeout: Property<Int?>?

    @get:Option(option = "retries", description = "The number of download retries.")
    @get:Optional
    @get:Incubating
    @get:Input
    abstract val retries: Property<Int?>?

    @get:Option(option = "retry-back-off-ms", description = "The initial back off in milliseconds between retries (doubles on each failure).")
    @get:Optional
    @get:Incubating
    @get:Input
    abstract val retryBackOffMs: Property<Int?>?

    @get:Option(option = "validate-url", description = "Sets task to validate the configured distribution url.")
    @get:Input
    @get:Incubating
    abstract val validateDistributionUrl: Property<Boolean?>?

    @get:Inject
    protected abstract val fileLookup: FileLookup?

    companion object {
        val DEFAULT_DISTRIBUTION_PARENT_NAME: String = WrapperDefaults.DISTRIBUTION_PATH

        private const val DISTRIBUTION_URL_EXCEPTION_MESSAGE = "Test of distribution url %s failed. Please check the values set with --gradle-distribution-url and --gradle-version."

        private fun getDistributionUri(uriRoot: File?, url: String): URI {
            try {
                return convertDistributionUrl(url, uriRoot)
            } catch (e: URISyntaxException) {
                throw GradleException("Distribution URL String cannot be parsed: " + url, e)
            }
        }
    }
}
