/*
 * Copyright 2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * A [org.gradle.api.Plugin] for generating IDEA files.
 */
package org.gradle.plugins.ide.idea

import org.gradle.plugins.ide.internal.IdePlugin.getLifecycleTask
import org.gradle.plugins.ide.internal.IdePlugin.Companion.withDescription
import org.gradle.plugins.ide.internal.IdePluginHelper.withGracefulDegradation
import org.gradle.plugins.ide.internal.IdePlugin.getCleanTask
import org.gradle.plugins.ide.internal.IdeArtifactRegistry.getIdeProjectFiles
import org.gradle.plugins.ide.eclipse.model.EclipseModel.project
import org.gradle.plugins.ide.eclipse.model.EclipseProject.name
import org.gradle.plugins.ide.internal.configurer.UniqueProjectNameProvider.getUniqueName
import org.gradle.plugins.ide.api.GeneratorTask.inputFile
import org.gradle.plugins.ide.api.GeneratorTask.outputFile
import org.gradle.plugins.ide.internal.IdePlugin.addWorker
import org.gradle.plugins.ide.eclipse.model.EclipseProject.buildCommand
import org.gradle.plugins.ide.eclipse.model.EclipseProject.natures
import org.gradle.plugins.ide.eclipse.internal.LinkedResourcesCreator.links
import org.gradle.plugins.ide.eclipse.model.EclipseProject.buildCommands
import org.gradle.plugins.ide.eclipse.model.BuildCommand.name
import org.gradle.plugins.ide.internal.IdeArtifactRegistry.registerIdeProject
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.baseSourceOutputDir
import org.gradle.plugins.ide.eclipse.model.EclipseModel.setClasspath
import org.gradle.plugins.ide.eclipse.model.EclipseModel.getClasspath
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.testSourceSets
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.testConfigurations
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.file
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.sourceSets
import org.gradle.plugins.ide.eclipse.internal.AfterEvaluateHelper.afterEvaluateOrExecute
import org.gradle.internal.deprecation.DeprecationLogger.whileDisabled
import org.gradle.plugins.ide.eclipse.model.EclipseModel.jdt
import org.gradle.plugins.ide.eclipse.model.EclipseJdt.javaRuntimeName
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.containers
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.containsTestFixtures
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.plusConfigurations
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.minusConfigurations
import org.gradle.plugins.ide.eclipse.model.internal.EclipseJavaVersionMapper.toEclipseJavaVersion
import org.gradle.plugins.ide.internal.IdePlugin.Companion.dependsOn
import org.gradle.plugins.ide.internal.IdePlugin.cleanName
import org.gradle.plugins.ide.eclipse.model.EclipseModel.getWtp
import org.gradle.plugins.ide.eclipse.model.EclipseWtp.component
import org.gradle.plugins.ide.eclipse.model.EclipseWtpComponent.rootConfigurations
import org.gradle.plugins.ide.eclipse.model.EclipseWtpComponent.libConfigurations
import org.gradle.plugins.ide.api.FileContentMerger.whenMerged
import org.gradle.plugins.ide.eclipse.model.internal.WtpClasspathAttributeSupport.enhance
import org.gradle.plugins.ide.eclipse.model.EclipseWtpComponent.classesDeployPath
import org.gradle.plugins.ide.eclipse.model.EclipseWtpComponent.minusConfigurations
import org.gradle.plugins.ide.eclipse.model.EclipseWtp.facet
import org.gradle.api.JavaVersion.toString
import org.gradle.plugins.ide.internal.IdeArtifactRegistry.getIdeProject
import org.gradle.plugins.ide.idea.model.internal.IdeaDependenciesOptimizer.optimizeDeps
import org.gradle.plugins.ide.internal.resolver.UnresolvedIdeDependencyHandler.log
import org.gradle.internal.service.ServiceRegistry.get
import org.gradle.plugins.ide.internal.resolver.IdeDependencySet.visit
import org.gradle.plugins.ide.idea.model.PathFactory.path
import org.gradle.plugins.ide.idea.model.SingleEntryModuleLibrary.moduleVersion
import org.gradle.plugins.ide.idea.model.ModuleLibrary.sources
import org.gradle.plugins.ide.idea.model.ModuleLibrary.javadoc
import org.gradle.plugins.ide.internal.resolver.UnresolvedIdeDependencyHandler.asFile
import org.gradle.plugins.ide.idea.model.PathFactory.relativePath
import org.gradle.plugins.ide.idea.model.ProjectLibrary.setName
import org.gradle.plugins.ide.idea.model.ProjectLibrary.classes
import org.gradle.plugins.ide.idea.model.ProjectLibrary.javadoc
import org.gradle.plugins.ide.idea.model.ProjectLibrary.sources
import org.gradle.plugins.ide.idea.model.Path.url
import org.gradle.plugins.ide.idea.model.Path.relPath
import org.gradle.plugins.ide.idea.model.Jdk.isAssertKeyword
import org.gradle.plugins.ide.idea.model.Jdk.isJdk15
import org.gradle.plugins.ide.idea.model.Jdk.languageLevel
import org.gradle.plugins.ide.idea.model.Jdk.projectJdkName
import org.gradle.plugins.ide.internal.generator.XmlPersistableConfigurationObject.xml
import org.gradle.plugins.ide.idea.model.ProjectLibrary.addToNode
import org.gradle.internal.Cast.uncheckedCast
import org.gradle.plugins.ide.idea.model.Jdk.hashCode
import org.gradle.plugins.ide.internal.IdeDeprecations.nagDeprecatedType
import org.gradle.plugins.ide.internal.IdeDeprecations.nagDeprecatedProperty
import org.gradle.plugins.ide.idea.model.IdeaModuleIml.generateTo
import org.gradle.plugins.ide.api.FileContentMerger.beforeMerged
import org.gradle.plugins.ide.idea.model.IdeaLanguageLevel.level
import org.gradle.plugins.ide.idea.model.Module.configure
import org.gradle.plugins.ide.internal.IdeArtifactRegistry.getIdeProjects
import org.gradle.plugins.ide.internal.IdeArtifactRegistry.Reference.owningProject
import org.gradle.plugins.ide.internal.IdeArtifactRegistry.Reference.get
import org.gradle.plugins.ide.internal.IdeProjectMetadata.file
import org.gradle.plugins.ide.api.XmlFileContentMerger.withXml
import org.gradle.plugins.ide.idea.model.ModuleLibrary.classes
import org.gradle.plugins.ide.idea.model.FilePath.file
import org.gradle.plugins.ide.idea.model.ProjectLibrary.getName
import org.gradle.plugins.ide.idea.model.ProjectLibrary.type
import org.gradle.plugins.ide.idea.model.ProjectLibrary.compilerClasspath
import org.gradle.plugins.ide.internal.IdePlugin.isRoot
import org.gradle.plugins.ide.idea.model.IdeaWorkspace.setIws
import org.gradle.api.JavaVersion.Companion.current
import org.gradle.plugins.ide.idea.model.PathFactory.addPathVariable
import org.gradle.plugins.ide.internal.IdePlugin.addWorkspace
import org.gradle.plugins.ide.idea.model.IdeaLanguageLevel.equals
import org.gradle.internal.deprecation.DeprecationLogger.deprecateTask
import org.gradle.internal.deprecation.DeprecationMessageBuilder.willBeRemovedInGradle10
import org.gradle.internal.deprecation.Documentation.AbstractBuilder.withUpgradeGuideSection
import org.gradle.internal.deprecation.DeprecationMessageBuilder.WithDocumentation.nagUser
import org.gradle.plugins.ide.api.GeneratorTask.generate
import org.gradle.plugins.ide.api.XmlGeneratorTask.xmlTransformer
import org.gradle.plugins.ide.api.XmlFileContentMerger.xmlTransformer
import org.gradle.plugins.ide.internal.tooling.GradleProjectBuilderInternal.buildForRoot
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaProject.setName
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaProject.setJdkName
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaProject.setLanguageLevel
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaProject.setJavaLanguageSettings
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaJavaLanguageSettings.setSourceLanguageLevel
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaJavaLanguageSettings.setTargetBytecodeVersion
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaJavaLanguageSettings.setJdk
import org.gradle.plugins.ide.internal.tooling.java.DefaultInstalledJdk.Companion.current
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaProject.setChildren
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModule.setDependencies
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModule.setName
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModule.setParent
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModule.setGradleProject
import org.gradle.plugins.ide.internal.tooling.model.DefaultGradleProject.findByPath
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModule.setContentRoots
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModule.setJdkName
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModule.setCompilerOutput
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModule.setJavaLanguageSettings
import org.gradle.plugins.ide.internal.tooling.TasksFactory.collectTasks
import org.gradle.plugins.ide.internal.configurer.EclipseModelAwareUniqueProjectNameProvider.setReservedProjectNames
import org.gradle.plugins.ide.internal.configurer.EclipseModelAwareUniqueProjectNameProvider.getUniqueName
import org.gradle.plugins.ide.eclipse.model.EclipseProject.comment
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.setGradleProject
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.classpath
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.setProjectDependencies
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.setSourceDirectories
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.classpathContainers
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.setAutoBuildTasks
import org.gradle.plugins.ide.eclipse.model.EclipseModel.getAutoBuildTasks
import org.gradle.plugins.ide.eclipse.model.EclipseProject.file
import org.gradle.plugins.ide.eclipse.model.Project.configure
import org.gradle.plugins.ide.eclipse.model.EclipseProject.mergeXmlProject
import org.gradle.plugins.ide.internal.tooling.TasksFactory.getTasks
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.isProjectDependenciesOnly
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.resolveDependencies
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.fileReferenceFactory
import org.gradle.plugins.ide.eclipse.model.EclipseClasspath.mergeXmlClasspath
import org.gradle.plugins.ide.eclipse.model.Classpath.entries
import org.gradle.plugins.ide.eclipse.model.AbstractLibrary.getLibrary
import org.gradle.plugins.ide.eclipse.model.FileReference.file
import org.gradle.plugins.ide.eclipse.model.AbstractLibrary.sourcePath
import org.gradle.plugins.ide.eclipse.model.AbstractLibrary.getJavadocPath
import org.gradle.plugins.ide.eclipse.model.AbstractLibrary.moduleVersion
import org.gradle.plugins.ide.eclipse.model.AbstractClasspathEntry.isExported
import org.gradle.plugins.ide.eclipse.model.UnresolvedLibrary.attemptedSelector
import org.gradle.plugins.ide.eclipse.model.AbstractClasspathEntry.path
import org.gradle.plugins.ide.eclipse.model.ProjectDependency.publicationSourcePath
import org.gradle.plugins.ide.eclipse.model.ProjectDependency.publicationJavadocPath
import org.gradle.plugins.ide.eclipse.model.ProjectDependency.publication
import org.gradle.plugins.ide.eclipse.model.ProjectDependency.getBuildDependencies
import org.gradle.plugins.ide.eclipse.model.SourceFolder.excludes
import org.gradle.plugins.ide.eclipse.model.SourceFolder.includes
import org.gradle.plugins.ide.eclipse.model.SourceFolder.output
import org.gradle.plugins.ide.eclipse.model.SourceFolder.getDir
import org.gradle.plugins.ide.eclipse.model.Output.path
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.tasks
import org.gradle.plugins.ide.eclipse.model.Project.linkedResources
import org.gradle.plugins.ide.eclipse.model.Link.name
import org.gradle.plugins.ide.eclipse.model.Link.type
import org.gradle.plugins.ide.eclipse.model.Link.location
import org.gradle.plugins.ide.eclipse.model.Link.locationUri
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.linkedResources
import org.gradle.plugins.ide.eclipse.model.Project.natures
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.projectNatures
import org.gradle.plugins.ide.eclipse.model.Project.buildCommands
import org.gradle.plugins.ide.eclipse.model.BuildCommand.arguments
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.buildCommands
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseJavaSourceSettings.setSourceLanguageLevel
import org.gradle.plugins.ide.eclipse.model.EclipseJdt.getSourceCompatibility
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseJavaSourceSettings.setTargetBytecodeVersion
import org.gradle.plugins.ide.eclipse.model.EclipseJdt.getTargetCompatibility
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseJavaSourceSettings.setJdk
import org.gradle.util.internal.CollectionUtils.findFirst
import org.gradle.plugins.ide.internal.tooling.eclipse.DefaultEclipseProject.getGradleProject
import org.gradle.plugins.ide.internal.tooling.model.DefaultGradleProject.path
import org.gradle.plugins.ide.eclipse.model.AbstractClasspathEntry.entryAttributes
import org.gradle.plugins.ide.eclipse.model.AbstractClasspathEntry.accessRules
import org.gradle.plugins.ide.eclipse.model.AccessRule.kind
import org.gradle.plugins.ide.eclipse.model.AccessRule.pattern
import org.gradle.internal.service.ServiceRegistration.addProvider
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaSourceDirectory.setDirectory
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaSourceDirectory.setGenerated
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaCompilerOutput.setInheritOutputDirs
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaCompilerOutput.setOutputDir
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaCompilerOutput.setTestOutputDir
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaSingleEntryLibraryDependency.setFile
import org.gradle.plugins.ide.idea.model.SingleEntryModuleLibrary.libraryFile
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaSingleEntryLibraryDependency.setSource
import org.gradle.plugins.ide.idea.model.SingleEntryModuleLibrary.sourceFile
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaSingleEntryLibraryDependency.setJavadoc
import org.gradle.plugins.ide.idea.model.SingleEntryModuleLibrary.javadocFile
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaSingleEntryLibraryDependency.setScope
import org.gradle.plugins.ide.idea.model.ModuleLibrary.getScope
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaSingleEntryLibraryDependency.setExported
import org.gradle.plugins.ide.idea.model.ModuleLibrary.isExported
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaSingleEntryLibraryDependency.setGradleModuleVersion
import org.gradle.plugins.ide.idea.model.ModuleDependency.name
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModuleDependency.setExported
import org.gradle.plugins.ide.idea.model.ModuleDependency.isExported
import org.gradle.plugins.ide.internal.tooling.idea.DefaultIdeaModuleDependency.setScope
import org.gradle.plugins.ide.idea.model.ModuleDependency.getScope
import org.gradle.StartParameter.taskNames
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.name
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.jdkName
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.setContentRoot
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.compilerOutput
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.explicitSourceLanguageLevel
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.explicitTargetBytecodeVersion
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.javaSourceCompatibility
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.javaTargetCompatibility
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.dependencies
import org.gradle.plugins.ide.internal.tooling.idea.IsolatedIdeaModuleInternal.getContentRoot

