plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Public API interfaces for input normalization"

dependencies {
    api(projects.baseServices)
    implementation(projects.stdlibJavaExtensions)
    compileOnly(libs.jspecify)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
