plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "A set of generic services and utilities specific for Groovy."

dependencies {
    api(projects.baseServices)
    api(projects.stdlibJavaExtensions)

    api(libs.jspecify)
    api(libs.groovy)
    api(libs.guava)

    testImplementation(testFixtures(projects.core))
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
