plugins {
    id("gradlebuild.distribution.api-java")
    id("gradlebuild.publish-public-libraries")
    kotlin("jvm")
}

description = "Tools for creating secure hashes for files and other content"

dependencies {
    api(projects.stdlibJavaExtensions)

    api(libs.jspecify)

    implementation(libs.guava)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
