plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Implementation of model reflection"

dependencies {
    api(projects.baseServices)
    api(projects.coreApi)
    api(projects.logging)
    api(projects.persistentCache)
    api(projects.problemsApi)
    api(projects.stdlibJavaExtensions)

    api(libs.guava)
    api(libs.jspecify)

    implementation(libs.commonsLang)
    implementation(libs.groovy)
    implementation(libs.inject)

    testImplementation(testFixtures(projects.persistentCache))
    testImplementation(testFixtures(projects.core))

    testFixturesApi(projects.internalIntegTesting)
    testFixturesImplementation(libs.guava)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
