plugins {
    id("gradlebuild.distribution.api-java")
    id("gradlebuild.publish-public-libraries")
    kotlin("jvm")
}

description = "Common shared build cache classes"

dependencies {
    compileOnly(libs.jspecify)

    api(projects.files)
    api(projects.hashing)

    testImplementation(testFixtures(projects.hashing))
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
