plugins {
    id("gradlebuild.distribution.implementation-java")
    id("gradlebuild.publish-public-libraries")
    kotlin("jvm")
}

description = "Build operations are our way to inspect the process of executing a build"

dependencies {
    api(projects.stdlibJavaExtensions)
    api(projects.time)

    api(libs.jspecify)

    implementation(libs.fastutil)
    implementation(libs.slf4jApi)
    implementation(libs.guava)

    testFixturesCompileOnly(kotlin("stdlib"))
    testFixturesImplementation(libs.guava)

    testImplementation(testFixtures(projects.time))
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
