plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Implementation of the service registry framework"

dependencies {
    api(projects.serviceLookup)
    api(projects.serviceProvider)

    api(libs.jspecify)

    implementation(projects.collections)
    implementation(projects.concurrent)
    implementation(projects.stdlibJavaExtensions)

    implementation(libs.inject)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
