plugins {
    id("gradlebuild.distribution.api-java")
    id("gradlebuild.publish-public-libraries")
    kotlin("jvm")
}

description = "Base tools to work with files"

dependencies {
    api(projects.stdlibJavaExtensions)

    api(libs.jsr305)

    implementation(libs.guava)
    implementation(libs.slf4jApi)

    compileOnly(libs.jspecify)

    testImplementation(projects.native)
    testImplementation(projects.baseServices) {
        because("TextUtil is needed")
    }
    testImplementation(testFixtures(projects.native))
    implementation(kotlin("stdlib-jdk8"))
    testFixturesCompileOnly(kotlin("stdlib"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
