plugins {
    id("gradlebuild.distribution.implementation-java")
    kotlin("jvm")
}

description = "Internal interfaces and implementations for input normalization"

dependencies {
    api(projects.normalizationApi)
    api(projects.baseServices)
    api(projects.normalizationJava)
    api(projects.serviceProvider)
    api(projects.stdlibJavaExtensions)

    api(libs.jspecify)

    implementation(libs.guava)

    testImplementation(projects.internalTesting)

    integTestDistributionRuntimeOnly(projects.distributionsJvm)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
