plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Implements generation of groovydoc"

dependencies {
    api(projects.ant)
    api(projects.antWorker)
    api(projects.coreApi)

    implementation(projects.baseServices)
    implementation(projects.daemonServerWorker)
    implementation(libs.guava)

    compileOnly(libs.jspecify)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    requiredRuntimes {
        worker = true
    }
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
