plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "Logging API consumed by the Develocity plugin"

dependencies {
    api(projects.buildOperations)
    api(projects.loggingApi)
    api(projects.stdlibJavaExtensions)

    api(libs.jspecify)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
