plugins {
    id("gradlebuild.distribution.api-java")
    kotlin("jvm")
}

description = "A set of general-purpose resource abstractions"

dependencies {
    api(projects.credentialsApi)
    api(projects.stdlibJavaExtensions)
    api(projects.buildOperations)
    api(projects.hashing)
    api(projects.baseServices)
    api(projects.native)

    api(libs.jspecify)

    implementation(projects.files)

    implementation(libs.guava)
    implementation(libs.commonsIo)

    testImplementation(projects.processServices)
    testImplementation(projects.coreApi)
    testImplementation(projects.fileCollections)
    testImplementation(projects.snapshots)

    testImplementation(testFixtures(projects.core))

    integTestDistributionRuntimeOnly(projects.distributionsCore)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}


repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
