plugins {
    id("gradlebuild.distribution.api-java")
    id("gradlebuild.publish-public-libraries")
    kotlin("jvm")
}

description = "Package build cache results"

dependencies {
    api(projects.buildCacheBase)
    api(projects.files)
    api(projects.hashing)
    api(projects.snapshots)
    api(projects.stdlibJavaExtensions)

    api(libs.guava)

    implementation(libs.commonsCompress)
    implementation(libs.commonsIo)

    compileOnly(libs.jspecify)

    testImplementation(projects.fileCollections)
    testImplementation(projects.processServices)
    testImplementation(projects.resources)

    testImplementation(testFixtures(projects.baseServices))
    testImplementation(testFixtures(projects.core))
    testImplementation(testFixtures(projects.coreApi))
    testImplementation(testFixtures(projects.snapshots))
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
