/*
 * Copyright 2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.buildinit.plugins.internal

import org.gradle.buildinit.plugins.internal.modifiers.BuildInitTestFramework
import org.gradle.buildinit.plugins.internal.modifiers.ModularizationOption
import java.util.Optional

/**
 * Initializes a Gradle build, either by converting an existing build to Gradle or generating a new Gradle build.
 *
 *
 * This interface currently includes a bunch of methods that are related to build generation and should move to [BuildGenerator].
 */
interface BuildInitializer {
    /**
     * Unique and user-friendly ID for the type of the initialized build like 'java-application' or 'kotlin-library'.
     *
     *
     * Users can select the desired type by providing a value of a known ID on the command line.
     */
    val id: String?

    fun supportsJavaTargets(): Boolean

    /**
     * Can this type of project be split-up into multiple subprojects?
     */
    val modularizationOptions: MutableSet<ModularizationOption>?

    /**
     * Returns the set of DSLs supported for this type of project, in display order.
     */
    val dsls: MutableSet<BuildInitDsl>?

    /**
     * The preferred DSL to use for this type of project.
     */
    val defaultDsl: BuildInitDsl?

    /**
     * Does a project name make sense for this type of project?
     */
    fun supportsProjectName(): Boolean

    /**
     * Does a source package name make sense for this type of project?
     */
    fun supportsPackage(): Boolean

    /**
     * Returns the set of test frameworks supported for this type of project.
     */
    fun getTestFrameworks(modularizationOption: ModularizationOption): MutableSet<BuildInitTestFramework>?

    /**
     * Returns [BuildInitTestFramework.NONE] when no tests generated by default.
     */
    fun getDefaultTestFramework(modularizationOption: ModularizationOption): BuildInitTestFramework?

    val defaultProjectNames: MutableList<String>?

    /**
     * Returns a collection of further reading related to this type of build (may be empty).
     */
    fun getFurtherReading(settings: InitSettings): Optional<String>?

    /**
     * Generates content for the given build.
     */
    fun generate(settings: InitSettings)
}
