/*
 * Copyright 2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.buildinit.plugins.internal

import org.gradle.api.internal.DocumentationRegistry
import org.gradle.buildinit.plugins.internal.modifiers.BuildInitTestFramework
import org.gradle.buildinit.plugins.internal.modifiers.Language
import org.gradle.buildinit.plugins.internal.modifiers.ModularizationOption
import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform
import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform.Companion.host
import java.util.Optional

abstract class CppProjectInitDescriptor(private val templateOperationFactory: TemplateOperationFactory, private val documentationRegistry: DocumentationRegistry) :
    LanguageLibraryProjectInitDescriptor() {
    override fun getLanguage(): Language {
        return Language.CPP
    }

    override fun generateProjectBuildScript(projectName: String, settings: InitSettings, buildScriptBuilder: BuildScriptBuilder) {
        buildScriptBuilder
            .fileComment("This generated file contains a sample C++ project to get you started.")
            .fileComment(documentationRegistry.getDocumentationRecommendationFor("details on building C++ applications and libraries", "building_cpp_projects"))
        configureBuildScript(settings, buildScriptBuilder)
    }

    override fun generateConventionPluginBuildScript(conventionPluginName: String, settings: InitSettings, buildScriptBuilder: BuildScriptBuilder) {
    }

    override fun generateSources(settings: InitSettings, templateFactory: TemplateFactory) {
        val sourceTemplate = sourceTemplateOperation(settings)
        val headerTemplate = headerTemplateOperation(settings)
        val testSourceTemplate = testTemplateOperation(settings)

        templateFactory.whenNoSourcesAvailable(sourceTemplate, headerTemplate, testSourceTemplate).generate()
    }

    override fun getTestFrameworks(modularizationOption: ModularizationOption): MutableSet<BuildInitTestFramework> {
        return mutableSetOf<BuildInitTestFramework>(BuildInitTestFramework.CPPTest)
    }

    override fun getDefaultTestFramework(modularizationOption: ModularizationOption): BuildInitTestFramework {
        return BuildInitTestFramework.CPPTest
    }

    override fun getFurtherReading(settings: InitSettings): Optional<String> {
        return Optional.of<String>(documentationRegistry.getSampleForMessage("building_cpp_" + getComponentType().pluralName()))
    }

    protected abstract fun sourceTemplateOperation(settings: InitSettings): TemplateOperation

    protected abstract fun headerTemplateOperation(settings: InitSettings): TemplateOperation

    protected abstract fun testTemplateOperation(settings: InitSettings): TemplateOperation

    protected open fun configureBuildScript(settings: InitSettings, buildScriptBuilder: BuildScriptBuilder) {
    }

    override fun supportsPackage(): Boolean {
        return false
    }

    protected val hostTargetMachineDefinition: String
        get() {
            val host = host()
            return buildNativeHostTargetDefinition(host)
        }

    fun fromCppTemplate(template: String, settings: InitSettings, sourceSetName: String, sourceDir: String): TemplateOperation {
        val targetFileName = template.substring(template.lastIndexOf("/") + 1).replace(".template", "")
        return fromCppTemplate(template, targetFileName, settings, sourceSetName, sourceDir)
    }

    fun fromCppTemplate(template: String, targetFileName: String, settings: InitSettings, sourceSetName: String, sourceDir: String): TemplateOperation {
        require(!(settings == null || settings.getProjectName().isEmpty())) { "Project name cannot be empty for a C++ project" }

        val namespace = NamespaceBuilder.toNamespace(settings.getProjectName())

        return templateOperationFactory.newTemplateOperation()
            .withTemplate(template)
            .withTarget(settings.getTarget().file(settings.getSubprojects().get(0) + "/src/" + sourceSetName + "/" + sourceDir + "/" + targetFileName).getAsFile())
            .withBinding("projectName", settings.getProjectName())
            .withBinding("namespace", namespace)
            .withBinding("fileComment", if (settings.isWithComments()) "This source file was generated by the Gradle 'init' task" else "")
            .create()
    }

    companion object {
        fun buildNativeHostTargetDefinition(host: DefaultNativePlatform): String {
            var definition = "machines."

            if (host.operatingSystem!!.isWindows) {
                definition += "windows"
            } else if (host.operatingSystem!!.isMacOsX) {
                definition += "macOS"
            } else if (host.operatingSystem!!.isLinux) {
                definition += "linux"
            } else {
                definition += "os(\"" + host.operatingSystem!!.toFamilyName() + "\")"
            }

            definition += "."

            if (host.architecture!!.isI386()) {
                definition += "x86"
            } else if (host.architecture!!.isAmd64()) {
                definition += "x86_64"
            } else {
                definition += "architecture(\"" + host.architecture!!.getName() + "\")"
            }

            return definition
        }
    }
}
