/*
 * Copyright 2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.buildinit.plugins.internal

import org.gradle.internal.UncheckedException.Companion.throwAsUncheckedException
import java.io.IOException
import java.io.PrintWriter
import java.nio.charset.StandardCharsets
import java.nio.file.Files

class GradlePropertiesGenerator : BuildContentGenerator {
    override fun generate(settings: InitSettings, buildContentGenerationContext: BuildContentGenerationContext) {
        generate(settings)
    }

    companion object {
        fun generate(settings: InitSettings) {
            val file = settings.getTarget().file("gradle.properties").getAsFile()
            try {
                PrintWriter(Files.newBufferedWriter(file.toPath(), StandardCharsets.UTF_8)).use { writer ->
                    if (settings.isWithComments()) {
                        writer.println("# This file was generated by the Gradle 'init' task.")
                        writer.println("# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties")
                        writer.println()
                    }
                    writer.println("org.gradle.configuration-cache=true")
                    if (settings.isUseIncubatingAPIs()) {
                        writer.println("org.gradle.parallel=true")
                        writer.println("org.gradle.caching=true")
                    }
                    writer.println()
                }
            } catch (e: IOException) {
                throw throwAsUncheckedException(e)
            }
        }
    }
}
