/*
 * Copyright 2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.buildinit.plugins.internal

import org.gradle.api.Action
import org.gradle.buildinit.plugins.internal.modifiers.Language
import org.gradle.buildinit.plugins.internal.modifiers.ModularizationOption
import java.util.Arrays

class TemplateFactory(private val initSettings: InitSettings, private val language: Language, private val templateOperationFactory: TemplateOperationFactory) {
    fun whenNoSourcesAvailable(vararg operations: TemplateOperation): TemplateOperation {
        return whenNoSourcesAvailable(initSettings.getSubprojects().get(0), Arrays.asList<TemplateOperation>(*operations))
    }

    fun whenNoSourcesAvailable(subproject: String, operations: MutableList<TemplateOperation>): TemplateOperation {
        return ConditionalTemplateOperation(org.gradle.internal.Factory {
            val mainFiles = initSettings.getTarget().dir(subproject + "/src/main/" + language.getName()).getAsFileTree()
            val testFiles = initSettings.getTarget().dir(subproject + "/src/test/" + language.getName()).getAsFileTree()
            mainFiles.isEmpty() || testFiles.isEmpty()
        }, operations)
    }

    fun fromSourceTemplate(clazzTemplate: String, sourceSetName: String, subprojectName: String): TemplateOperation {
        return fromSourceTemplate(clazzTemplate, sourceSetName, subprojectName, language)
    }

    @JvmOverloads
    fun fromSourceTemplate(clazzTemplate: String, sourceSetName: String, subprojectName: String = initSettings.getSubprojects().get(0), language: Language = this.language): TemplateOperation {
        return fromSourceTemplate(clazzTemplate, Action { t: SourceFileTemplate ->
            t.subproject(subprojectName)
            t.sourceSet(sourceSetName)
            t.language(language)
        })
    }

    fun fromSourceTemplate(sourceTemplate: String, config: Action<in SourceFileTemplate>): TemplateOperation {
        var targetFileName = sourceTemplate.substring(sourceTemplate.lastIndexOf("/") + 1).replace(".template", "")

        val details = TemplateDetails(language, targetFileName)
        config.execute(details)

        var basePackageName = ""
        var packageDecl = ""
        val className: String = (if (details.className == null) "" else details.className)!!
        if (initSettings != null) {
            basePackageName = initSettings.getPackageName()
            var packageName = basePackageName
            if (initSettings.getModularizationOption() == ModularizationOption.WITH_LIBRARY_PROJECTS) {
                packageName = joinIfNotEmpty(packageName, ".") + details.subproject
            }
            packageDecl = joinIfNotEmpty("package ", packageName)
            targetFileName = joinIfNotEmpty(packageName.replace(".", "/"), "/") + details.targetFileName
        } else {
            targetFileName = details.targetFileName
        }

        val operationBuilder = templateOperationFactory.newTemplateOperation()
            .withTemplate(sourceTemplate)
            .withTarget(initSettings.getTarget().file(details.subproject + "/src/" + details.sourceSet + "/" + details.language.getName() + "/" + targetFileName).getAsFile())
            .withBinding("basePackagePrefix", joinIfNotEmpty(basePackageName, "."))
            .withBinding("packageDecl", packageDecl)
            .withBinding("className", className)
            .withBinding("fileComment", if (initSettings.isWithComments()) "This source file was generated by the Gradle 'init' task" else "")
        for (entry in details.bindings.entries) {
            operationBuilder.withBinding(entry.key, entry.value)
        }
        return operationBuilder.create()
    }

    private class TemplateDetails(var language: Language, var fileName: String) : SourceFileTemplate {
        val bindings: MutableMap<String, String> = HashMap<String, String>()
        var subproject: String? = null
        var sourceSet: String = "main"
        var className: String? = null

        override fun subproject(subproject: String) {
            this.subproject = subproject
        }

        override fun sourceSet(name: String) {
            this.sourceSet = name
        }

        override fun language(language: Language) {
            this.language = language
        }

        override fun className(name: String) {
            this.className = name
        }

        override fun binding(name: String, value: String) {
            this.bindings.put(name, value)
        }

        val targetFileName: String
            get() {
                if (className != null) {
                    return className + "." + language.getExtension()
                }
                return fileName
            }
    }

    protected interface SourceFileTemplate {
        fun sourceSet(name: String)

        fun language(language: Language)

        fun className(name: String)

        fun binding(name: String, value: String)

        fun subproject(subproject: String)
    }

    companion object {
        private fun joinIfNotEmpty(left: String, right: String): String {
            return if (left.isEmpty() || right.isEmpty()) "" else (left + right)
        }
    }
}

