/*
 * Copyright 2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.buildinit.plugins.internal

import org.gradle.api.file.Directory
import org.gradle.internal.UncheckedException.Companion.throwAsUncheckedException
import org.gradle.util.internal.GFileUtils
import org.jspecify.annotations.NullMarked
import java.io.IOException
import java.io.PrintWriter
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.util.Arrays
import java.util.function.Function

/**
 * Generates version catalogs based on versions, libraries and plugins tracked in the BuildContentGenerationContext's VersionCatalogDependencyRegistry.
 */
@NullMarked
class VersionCatalogGenerator private constructor(private val target: Directory) {
    fun generate(buildContentGenerationContext: BuildContentGenerationContext, withComments: Boolean) {
        val gradleDirectory = target.getAsFile().toPath().resolve("gradle")
        GFileUtils.mkdirs(gradleDirectory.toFile())

        try {
            PrintWriter(Files.newBufferedWriter(gradleDirectory.resolve("libs.versions.toml"), StandardCharsets.UTF_8)).use { writer ->
                if (withComments) {
                    writer.println("# This file was generated by the Gradle 'init' task.")
                    writer.println("# https://docs.gradle.org/current/userguide/version_catalogs.html#sec::toml-dependencies-format")
                }
                var needsSeparatorLine = withComments
                for (section in getSections(buildContentGenerationContext)) {
                    needsSeparatorLine = section.write(writer, needsSeparatorLine)
                }
            }
        } catch (e: IOException) {
            throw throwAsUncheckedException(e)
        }
    }

    private class Section<T>(private val header: String, private val items: MutableCollection<T?>, private val formatter: Function<T?, String>) {
        /**
         * Returns true if anything was written.
         */
        fun write(writer: PrintWriter, needsSeparatorLine: Boolean): Boolean {
            if (items.isEmpty()) {
                return false
            }

            if (needsSeparatorLine) {
                writer.println()
            }

            writer.println(header)
            for (item in items) {
                writer.println(formatter.apply(item))
            }

            return true
        }
    }

    companion object {
        fun create(target: Directory): VersionCatalogGenerator {
            return VersionCatalogGenerator(target)
        }

        private fun getSections(buildContentGenerationContext: BuildContentGenerationContext): MutableList<Section<*>> {
            val versionCatalogDependencyRegistry = buildContentGenerationContext.getVersionCatalogDependencyRegistry()

            return Arrays.asList<Section<*>>(
                VersionCatalogGenerator.Section<VersionCatalogDependencyRegistry.VersionEntry?>(
                    "[versions]",
                    versionCatalogDependencyRegistry.getVersions(),
                    Function { v: VersionCatalogDependencyRegistry.VersionEntry? -> String.format("%s = \"%s\"", v!!.alias, v.version) }
                ),
                VersionCatalogGenerator.Section<VersionCatalogDependencyRegistry.LibraryEntry?>(
                    "[libraries]",
                    versionCatalogDependencyRegistry.getLibraries(),
                    Function { l: VersionCatalogDependencyRegistry.LibraryEntry? -> String.format("%s = { module = \"%s\", version.ref = \"%s\" }", l!!.alias, l.module, l.versionRef) }
                ),
                VersionCatalogGenerator.Section<VersionCatalogDependencyRegistry.PluginEntry?>(
                    "[plugins]",
                    versionCatalogDependencyRegistry.getPlugins(),
                    Function { p: VersionCatalogDependencyRegistry.PluginEntry? -> String.format("%s = { id = \"%s\", version = \"%s\" }", p!!.alias, p.pluginId, p.version) }
                )
            )
        }
    }
}
