plugins {
    id("gradlebuild.distribution.implementation-java")
    id("gradlebuild.publish-public-libraries")
    kotlin("jvm")
}

description = "Tools to work with functional code, including data structures"

dependencies {
    api(libs.jspecify)
    api(projects.stdlibJavaExtensions)

    implementation(libs.fastutil)
    implementation(libs.guava)
    implementation(libs.jsr305)
    implementation(kotlin("stdlib-jdk8"))
}

gradleModule {
    computedRuntimes {
        // Auto-generated by `:checkTargetRuntimes --fix`
        client = true
        daemon = true
        worker = true
    }
}

errorprone {
    nullawayEnabled = true
}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(17)
}
