/*
 * Copyright 2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.gradle.api.plugins.catalog.internal

import org.gradle.api.internal.artifacts.ImmutableVersionConstraint
import org.gradle.api.internal.catalog.DefaultVersionCatalog
import org.gradle.api.internal.catalog.parser.TomlCatalogFileParser
import java.io.IOException
import java.io.Writer
import java.lang.String
import java.util.regex.Pattern
import java.util.stream.Collectors
import kotlin.RuntimeException
import kotlin.collections.ArrayList
import kotlin.collections.MutableList
import kotlin.collections.plus
import kotlin.plus
import kotlin.sequences.plus
import kotlin.text.StringBuilder
import kotlin.text.isEmpty
import kotlin.text.plus

internal class TomlWriter(private val writer: Writer) {
    private fun writeLn(line: String = ""): TomlWriter {
        return write(line + "\n")
    }

    private fun write(text: String): TomlWriter {
        try {
            writer.write(text)
        } catch (ex: IOException) {
            throw RuntimeException(ex)
        }
        return this
    }

    fun generate(model: DefaultVersionCatalog) {
        writeHeader()
        writeMetadata()
        writeVersions(model)
        writeLibraries(model)
        writeBundles(model)
        writePlugins(model)
    }

    private fun writeVersions(model: DefaultVersionCatalog) {
        val versions = model.versionAliases
        if (versions.isEmpty()) {
            return
        }
        writeTableHeader("versions")
        for (alias in versions) {
            write(normalizeForToml(alias) + " = ")
            writeLn(versionString(model.getVersion(alias).version))
        }
        writeLn()
    }

    private fun writeLibraries(model: DefaultVersionCatalog) {
        val aliases = model.libraryAliases
        if (aliases.isEmpty()) {
            return
        }
        writeTableHeader("libraries")
        for (alias in aliases) {
            val data = model.getDependencyData(alias)
            val group = data.group
            val name = data.name
            val versionRef = data.versionRef
            val version = data.getVersion()
            val sb = StringBuilder()
            sb.append(normalizeForToml(alias))
                .append(" = {")
                .append(keyValuePair("group", group))
                .append(", ")
                .append(keyValuePair("name", name))
                .append(", ")
            if (versionRef != null) {
                sb.append(keyValuePair("version.ref", normalizeForToml(versionRef)))
            } else {
                sb.append("version = ").append(versionString(version))
            }
            sb.append(" }")
            writeLn(sb.toString())
        }
        writeLn()
    }

    private fun writeBundles(model: DefaultVersionCatalog) {
        val aliases = model.bundleAliases
        if (aliases.isEmpty()) {
            return
        }
        writeTableHeader("bundles")
        for (alias in aliases) {
            val bundle = model.getBundle(alias).components
            writeLn(
                normalizeForToml(alias) + " = [" + bundle.stream()
                    .map<String> { alias: String? -> Companion.normalizeForToml(alias!!) }
                    .map<String> { string: String? -> Companion.quoted(string!!) }
                    .collect(Collectors.joining(", ")) + "]")
        }
        writeLn()
    }

    private fun writePlugins(model: DefaultVersionCatalog) {
        val aliases = model.pluginAliases
        if (aliases.isEmpty()) {
            return
        }
        writeTableHeader("plugins")
        for (alias in aliases) {
            val data = model.getPlugin(alias)
            val id = data.id
            val versionRef = data.versionRef
            val version = data.getVersion()
            val sb = StringBuilder()
            sb.append(normalizeForToml(alias))
                .append(" = {")
                .append(keyValuePair("id", id))
                .append(", ")
            if (versionRef != null) {
                sb.append(keyValuePair("version.ref", normalizeForToml(versionRef)))
            } else {
                sb.append("version = ").append(versionString(version))
            }
            sb.append(" }")
            writeLn(sb.toString())
        }
        writeLn()
    }

    private fun writeHeader() {
        writeLn("#")
        writeLn("# This file has been generated by Gradle and is intended to be consumed by Gradle")
        writeLn("#")
    }

    private fun writeMetadata() {
        writeLn("[metadata]")
        writeLn("format.version = \"" + TomlCatalogFileParser.CURRENT_VERSION + "\"")
        writeLn()
    }

    private fun writeTableHeader(title: String) {
        writeLn("[" + title + "]")
    }

    companion object {
        private val SEPARATOR: Pattern = Pattern.compile("[_.-]")

        private fun normalizeForToml(alias: String): String {
            return SEPARATOR.matcher(alias).replaceAll("-")
        }

        private fun versionString(version: ImmutableVersionConstraint): String {
            val requiredVersion = version.getRequiredVersion()
            val strictVersion = version.getStrictVersion()
            val preferredVersion = version.getPreferredVersion()
            val rejectedVersions = version.getRejectedVersions()
            val sb = StringBuilder()
            if (rejectedVersions.isEmpty() && strictVersion.isEmpty() && preferredVersion.isEmpty()) {
                // typical shortcut case, "foo='1.2'"
                sb.append(quoted(requiredVersion))
                return sb.toString()
            }
            sb.append("{ ")
            val parts: MutableList<String> = ArrayList<String>()
            if (!strictVersion.isEmpty()) {
                parts.add(keyValuePair("strictly", strictVersion))
            }
            if (!preferredVersion.isEmpty()) {
                parts.add(keyValuePair("prefer", preferredVersion))
            }
            if (!requiredVersion.isEmpty() && strictVersion.isEmpty()) {
                parts.add(keyValuePair("require", requiredVersion))
            }
            if (!rejectedVersions.isEmpty()) {
                if (rejectedVersions.contains("+")) {
                    parts.add("rejectAll = true")
                } else {
                    parts.add("reject = [" + rejectedVersions.stream().map<String> { string: String? -> Companion.quoted(string!!) }.collect(Collectors.joining(", ")) + "]")
                }
            }
            sb.append(String.join(", ", parts)).append(" }")
            return sb.toString()
        }

        private fun keyValuePair(key: kotlin.String, value: kotlin.String): kotlin.String {
            return key + " = " + quoted(value)
        }

        private fun quoted(string: kotlin.String): kotlin.String {
            return "\"" + string + "\""
        }
    }
}
